- name: 'Ping hosts'
  hosts: all
  tasks:
  - name: 'ping task'
    ping:
  - name: 'hostname check'
    command: 'hostname'
    register: cat_result
  - name: 'print hostname'
    debug:
      var: cat_result.stdout
